spring:
  application:
    name: springcloudconfigclient


server:
  port: 8004
message: "welcometo spring testing1"
management:
  endpoints:
    web:
      exposure:
        include: refresh



