spring:
  application:
    name: springcloudconfigclient


server:
  port: 8004
message: "welcometo spring testing12"
password: 3a120d24256ee0bcb80cd1cff2ae9a4f530cd311a0bbc7d34fad0c9effc7f13c
management:
  endpoints:
    web:
      exposure:
        include: refresh





